# This workflow will build and publish snapshots to our GitHub repository
name: Maven Package

on:
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: ./mvnw clean test javadoc:javadoc

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
